[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
EscrowDapp = "4XLs7eTjECzLwby7D9SwWbSZa9BjFvMrDZb7zEaVNC5k"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "devnet"
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx --test --test-reporter=spec tests/*.ts"
